# Generated by Django 5.2 on 2025-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsDb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('Room_Number', models.CharField(max_length=5)),
                ('Complaint_Type', models.CharField(max_length=100)),
                ('Complaint_Details', models.TextField()),
            ],
        ),
    ]
