# Generated by Django 5.2 on 2025-04-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsDb', '0002_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Full_name',
            new_name='Full_Name',
        ),
    ]
