# Generated by Django 5.2 on 2025-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsDb', '0003_rename_full_name_complaint_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='Null', upload_to=''),
            preserve_default=False,
        ),
    ]
