# Generated by Django 5.2 on 2025-04-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsDb', '0004_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
