# Generated by Django 5.2 on 2025-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsDb', '0005_complaint_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
