# Generated by Django 5.2 on 2025-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsDb', '0006_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
